#!/bin/bash
# Version: 1

function echoCommand () {
    echo -e "$(tput setab 12) $(tput sgr0)$(tput setaf 12)\uE0B0$(tput sgr0)$(tput setaf 9) $@$(tput sgr0) "
}

# Check script dependencies
if ! [ -x "$(command -v notify-send)" ]; then
    echo "The notify-send command isn't installed yet."
    echo "It lets us send notifications when updates are finished."
    echoCommand "sudo apt install libnotify-bin"
    sudo apt install libnotify-bin
fi

echoCommand "sudo apt update"
sudo apt update

result="$?"
if [ $result != 0 ]; then
    notify-send --icon="dialog-error" "Could Not Update" "Error while checking for updates."
    paplay /usr/share/sounds/KDE-Sys-App-Negative.ogg
    exit $result
fi

echo " "
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
bash "$DIR/upgradepackages"
